name: Publish to github docker

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  artifact_name: biligo-live-ws

on: create

jobs:
  publish_docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
    # only do when created a tag named docker-push
    if: github.ref == 'refs/tags/docker-push'
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ repository.owner }}/${{ github.repository }}:latest
          platforms: linux/arm64, linux/amd64, windows/amd64

      # after pushed image, remove the tag
      - name: Delete Tag
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
           tag_name: docker-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
