name: Test Pass

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    # this is for private go module
    - run: git config --global url.https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com/${{ github.actor }}.insteadOf https://github.com/${{ github.actor }}

    - name: Test
      run: go test -v ./...
