name: Test Pass

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GOPRIVATE: github.com/eric2788

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
