name: Test Pass

env:
  GOPRIVATE: github.com/eric2788

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: git config --global url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf https://github.com/
    - name: Test
      run: go test -v ./...
